const mongoose=require('mongoose');
const creatorSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
    },
    channel:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        required:true,
    },
    contact:{
        type:Number,
        required:true,
    },
    gender:{
        type:String,
    },
    password:{
        type:String,
        required:true,
    },
    content:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Video",
        }
    ],
});
module.exports=mongoose.model("Creator",creatorSchema);