const mongooose=require('mongoose');
const videoSchema=new mongooose.Schema({
    title:{
        type:String,
        required:true,
    },
    description:{
        type:String,
    },
    author:{
        type:String,
        required:true,
    },
    views:{
        type:Number,
    },
    creator:{
        type:mongooose.Schema.Types.ObjectId,
        ref:"Creator",
    },
    url:{
        type:String,
        required:true,
    },
    length:{
        type:String,
    },
    rating:{
        type:mongooose.Schema.Types.ObjectId,
        ref:"Rating",
    },
    createdAt:{
        type:Date,
        default:Date.now(),
        required:true,
    },
    tags:{
        type:[String],
    },
    garde:{
        type:String,
        required:true,
    },
    subject:{
        type:String,
        required:true,
    },
    lang:{
        type:String,
        required:true,
    },
    chapter:{
        type:String,
        required:true,
    },
    approved:{
        type:Boolean,
        default:false,
    }
});
module.exports=mongooose.model("Video",videoSchema);